//
// Created by Asus TUF on 6/22/2026.
//

#ifndef PHYSICS_ENGINE_CONFIG_H
#define PHYSICS_ENGINE_CONFIG_H
#define PARTICLE_COUNT 1
#define RIGIDBODY_COUNT 1
#define GRAVITY 9.81
#endif //PHYSICS_ENGINE_CONFIG_H
